  python main.py\
   --model=proto_dot\
   --trainN=5\
   --evalN=5\
   --K=10\
   --Q=1\
   --O=0\
   --distance_metric="proto"\
   --contrastive="Normal"\
   --temperature_alpha=0.5\
   --temperature_beta=0.1\
   --alpha=0.5\
   --beta=0.5\
   --threshold="mean"\
   --test\
   --load_ckpt="proto_dot_fewevent_5_10_20220623_152712"\
   --embedding_visualization_path="embedding_visualization/proto_hcl"\
   --seed=7324